# Site settings
title: Blog of Finesse
email: stupidlw@126.com
description: > # this means to ignore newlines until "baseurl:"
    岂能尽如人意
    但求无愧我心
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://someaddr.com" # the base hostname & protocol for your site
twitter_username: NULL
github_username:  brg-liuwei

# Build settings
markdown: kramdown
