# Site settings
title: Blog of Finesse
email: stupidlw@126.com
description: > # this means to ignore newlines until "baseurl:"
    心似明月常自在
    意如流水任东西
baseurl: /finesse  # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: NULL
github_username:  brg-liuwei

# Build settings
markdown: kramdown
